### ISSUE TITLE
Laplacian matrix

### ISSUE THREAD

**Issue by Jhayes77** [math434/social-networks-james-jacob-killian-luis#10]
If you need the Laplacian matrix to work on other problems, it is

$$
 L = \begin{bmatrix} 
2 & -1 & 0 & 0 & -1 & 0 \\
-1 & 3 & -1 & 0 & -1 & 0 \\
0 & -1 & 2 & -1 & 0 & 0 \\
0 & 0  & -1 & 3 & -1 & -1 \\
-1 & -1 & 0 & -1 & 3 & 0 \\
0 & 0 &  0 & -1 & 0 & 1 \\
\end{bmatrix}
$$

**Comment by kanderson15** [comment]
Its cool. I am going to look at my problems tomorrow.

**Comment by kanderson15** [comment]
Its in the master file.
