### ISSUE TITLE
Please merge pull requests in order that they are posted

### ISSUE THREAD

**Issue by JHaasIII92** [math434/social-networks-james-jacob-killian-luis#17]
Since we are working with a single notebook any pull made out of order will cause conflicts with the pull requests that came before.

Instead merge the open pull request or delete it

Then, if merged download a new copy of the master place your code in that note book

Finally create a pull request for that exercise

**Comment by kanderson15** [comment]
Alright, I misunderstood your text message.

**Comment by kanderson15** [comment]
The kernel issue has been fixed. Exercise #3 Branch should merge now. Exercise 9 was removed.

**Comment by kanderson15** [comment]
Closing this because the issues we had regarded the kernel.
